[package]
name = "rust-nes-emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35.2"
log = "0.4.17"
simple_logger = "4.0.0"
hex = "0.4.3"